# -*- coding: utf-8 -*-
"""pythan_basics_thangavelu.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqpe-ne5RhLiR_b_pNYgvD1nfC6vlvHI
"""

per_name="pratheik nandan"
per_age=8
per_height=1.68
if True:
  print("Name",per_name,"\nAge:",per_age,"\nHeight",per_height,"\nStudent is valid")

age_months=per_age*12
age_days=per_age*365
age_rem=per_age//7
age_pow=per_age**2
print("Age in months:",age_months,"\nAge in days",age_days,"\nAge divided with 7 remainder is",age_rem,"\nAge power of 2 is",age_pow)